### ISSUE TITLE
can we make this work with android phones?

### ISSUE THREAD

**Issue by leleleSDX** [Ryochan7/sc-controller#101]
![razer_kishi_review](https://github.com/Ryochan7/sc-controller/assets/6260996/bdf061a2-8b09-4c08-b7b9-59a71f66ea6e)

android phones especially telescophic controllers attached is the closest thing we have to a steamcontroller 2.0. phones have gyro and touch input. even using just the phone with touchscreen buttons should work. have an oldphone you don't use? turn it into a steamcontroller. if you have the budget, but a cheap telescophic controller off ebay and you have feature rich gamepad.

**Comment by Ryochan7** [comment]
Will likely never happen. Even some of the code for the current devices that SC Controller supports is kind of thrown together; Steam Deck support is still a bit flaky. It is probably not a good base to work from in the long run. I had ambitions to port my experimental mapper projects to Linux in some form but I do not think I will ever do it. Not enough time and I do not game on Linux anymore. The major adoption of Wine (Proton) in the "Linux" gaming space has seriously had a negative impact on Linux as a whole and software freedom; rms was right about Wine after all.
