### ISSUE TITLE
Steam Controller randomly disconnects when vibrations are played

### ISSUE THREAD

**Issue by Araly** [Ryochan7/sc-controller#14]
I'm using the controller with the USB dongle.

I'm playing the Witcher 3, everything goes fine until a fight occurs, and the controller dies, shuts down.

Then I press the steam button, it turns on again, and the light flashes, the controller is usable again,  I can move the cursor around and so. It stays in this state for a while.

If I return to the game, I can expect the controller to randomly shut off again at any point. I've been trying to see if it correlates with me pressing some specific key but it doesn't seem like it.

I don't have many games out of steam, so the Witcher 3 is kind of the only game I use sc-controller on at the moment, but I'll add info if I play another game and see other issues.

The gui told me it was recently updated to v0.4.8.1, so maybe that's a hint.

Let me know if there are other information I can give.

EDIT: the disconnections seem to happen whenever I get hurt, I received an explosion, and the controller disconnected. It might be because of the vibrations that happen whenever I get hurt. I disabled the vibrations, and haven't had a disconnection since.

**Comment by C0rn3j** [comment]
This sounds more like an issue with upstream sc-controller rather than the Python 3 fork, do you have the same issue with upstream sc-controller?

**Comment by Ryochan7** [comment]
I never liked how vibration works with SC-Controller so I have the option disabled. Unfortunately, I do not have a way to test that scenario. My compy's GPU does not support Vulkan so I have no way to use Proton to run the Witcher 3 on Linux.

**Comment by Araly** [comment]
Not long after this, the batteries died. Maybe the rumbling was too much for the low batteries ? Anyways, I changed the batteries and now this is not an issue anymore, so I'll close
