### ISSUE TITLE
Service not stopping after quitting program

### ISSUE THREAD

**Issue by julikaiba** [Ryochan7/sc-controller#25]
I might be missing something but when I right click and click quit in the taskbar the icon vanishes and I cant find the program in the taskmanager. However the settings still persist and when pressing the steam button, even the little popup window shows to let me switch between profiles or open the keyboard etc. 
Is there another background service or daemon that needs to be stopped? (this became a problem after the autoclicker i was trying to build using the repeat function didnt stop anymore and even quitting the program didnt change that fact)

**Comment by Ryochan7** [comment]
The default behavior is that the daemon keeps running after the GUI is closed. I don't like that default. I always change the setting on my end by enabling the **Automatically Disable Emulation When Closing GUI** option in the Settings window (located under the Advanced tab).

**Comment by julikaiba** [comment]
Thats exactly what I was looking for, thank you very much.
