### ISSUE TITLE
Add missing hipfire test

### ISSUE THREAD

**Issue by rnhmjoj** [Ryochan7/sc-controller#26]
Any chance you might pull this in? https://github.com/kozec/sc-controller/pull/603
Upstream is not responding...

**Comment by Ryochan7** [comment]
I can take a look at it but you can see I have not been much better when it comes to responding promptly. Working on DS4Windows takes up a lot of time especially over the past few weeks.

**Comment by Ryochan7** [comment]
Merged changes in commit e3d244424c1dcf80efa6e7cd0ff1ec6fd1361660

**Comment by rnhmjoj** [comment]
Thank you.
