### ISSUE TITLE
The menu option "Edit Bindings" crash entire OSD

### ISSUE THREAD

**Issue by ren2r** [Ryochan7/sc-controller#29]
Trying to use the OSD menu option "Edit Bindings" to edit the profile while in game, crashes the OSD and it can't be shown again until restart the daemon.

[Edit]
It happens with the AUR package version 0.4.8.4 in Archlinux, using the from git repository without installing it doesn't crash the OSD but the "Edit bindings window" doesn't show up

**Comment by Supreeeme** [comment]
I fixed this in my linked pull request, if you're interested in testing it out.

**Comment by ren2r** [comment]
@Supreeeme, It seems to be fixed in your branch.
In the tests I did it worked just fine without crashing the OSD.

**Comment by Ryochan7** [comment]
I'll have to take a look at that pull request in a bit. DS4Windows keeps me busy.
