### ISSUE TITLE
resetgyro() doesn't seem to do anything

### ISSUE THREAD

**Issue by gddgddg** [Ryochan7/sc-controller#41]
I sometimes find that I need to calibrate my Steam Controller's gyroscope in the middle of a game. I've bound resetgyro() to the analog stick click, but it doesn't seem to do anything. I've had instances where the gyroscope will be rapidly pulling in one direction, making it unusable, and resetting the gyroscope or restarting the daemon doesn't affect it. After a while it seems to reset itself, however.

**Comment by Ryochan7** [comment]
Looking at the code, it looks like the command only affects Gyro lean actions and add an offset based on the current controller orientation. The command will not do anything if you are using the Gyro mapped to the mouse.

**Comment by gddgddg** [comment]
I understand, thank you. It seems it would be useful if there were a calibration action that could be mapped to a button or menu item in case the gyro is pulling in one direction. There doesn't seem to be an obvious way to reset it in case that happens.
