### ISSUE TITLE
DualShock 4 no longer detected properly when plugged in

### ISSUE THREAD

**Issue by gddgddg** [Ryochan7/sc-controller#43]
When I plug in my DualShock 4, in the past the software would detect it and automatically switch to it. This no longer happens; instead, nothing happens, but I can register it as a "Sony Computer Entertainment Wireless Controller". If I register it this way, it doesn't detect the gyro, which is important for certain types of games. The controller is detected by other software, such as Steam, in which I can use the gyro and touchpad just fine.

I've tried this on two machines both running Arch Linux, where the issue persists

Edit: Just tried previous versions down to 0.4.8.3 and none of them detected my DS4 automatically, leading me to think it has to do with a system update.

**Comment by Ryochan7** [comment]
Not that sure. My DS4 v.2 is detected fine but my DS4 v.1 does not get detected.

**Comment by Ryochan7** [comment]
Only DS4 v.2 support was available in the ds4drv driver in SC Controller. Made a quick change so a Sony DS4 v.1 could also be detected. That works now as well.

https://github.com/Ryochan7/sc-controller/tree/76ebfefa4d88564d82f033baaa0b53b236bc8f88

**Comment by gddgddg** [comment]
Seems to be working fine now, thank you very much.
