### ISSUE TITLE
Cannot create new profiles with CSDs disabled

### ISSUE THREAD

**Issue by tyzoid** [Ryochan7/sc-controller#49]
While trying to create a new profile, no create/save button appears when CSDs are disabled. Enabling CSD for this app reveals an 'OK' button in the title menu.

![Profile creation. Top image: No CSD enabled, missing OK button. Bottom image: CSD enabled, OK button appears in titlebar](https://user-images.githubusercontent.com/974758/147721079-adbc957a-bc6b-4890-9f2b-76cc8af466f0.png)

Additionally, pressing the Enter/Return key does not create a profile while the text cursor is in the textbox.

**Comment by Ryochan7** [comment]
I cannot duplicate the problem with the OK button. I would assume there is no event set up to catch Enter being pressed when that textbox has focus. Not too worried about that one though.

**Comment by Ryochan7** [comment]
Not much to work on here. I cannot duplicate the original problem so I am going to close this issue.
