### ISSUE TITLE
Official-driver style "Joystick Camera" smooth

### ISSUE THREAD

**Issue by mochaaP** [Ryochan7/sc-controller#52]
Current implementation:

https://user-images.githubusercontent.com/21154023/153705083-3e4b4f3d-71ec-4850-8e75-ff3a94dd8594.mp4

Official implementation:

https://user-images.githubusercontent.com/21154023/153705216-45ea1705-75c3-4ac6-a25e-4266b59736de.mp4

Official driver does a smooth transition between pressed & non pressed state, making the camera smoother in most games.

**Comment by Ryochan7** [comment]
The Steam Input implementation has somewhat aggressive smoothing enabled by default. SC Controller doesn't add smoothing to that output type by default IIRC. Adding smoothing and playing with the parameters would probably help a fair amount.

Not entirely sure how accurate the final output would be from the output though. I mostly map the Steam Controller to a virtual KB+M config.

**Comment by mochaaP** [comment]
I noticed that the "Smooth" checkbox in the configuration interface is disabled for Joystick Camera. Not sure if it's intended or it's only for mouse output?

**Comment by Ryochan7** [comment]
SC Controller actively removes support for Smoothing when the XY action points to AxisAction instances which would be used in this case. AxisAction does not allow smoothing to be used for some reason. Might have to look into changing that.

**Comment by Ryochan7** [comment]
Looks like I will not get around to changing it
