### ISSUE TITLE
launch sc-controller in the background

### ISSUE THREAD

**Issue by rebeccaRossRobotics** [Ryochan7/sc-controller#86]
Hi!
I'm trying to get the sc-controller to run automatically in the background when the user logs in. I have a system service that runs a script that calls `./run.sh` at login but it fails due to not having access to a display.

Is there a way to launch the sc-controller to the background without the need of a display?

For context this is the srcipt which calls `./run.sh`
```
#!/bin/sh

echo "opening controller driver"
cd
cd /home/deck/sc-controller
sudo ./run.sh &
sleep 2
xdotool search "sc controller" windowminimize
sleep 10
xdotool search "sc controller" windowclose
```

And the system service is:
```
[Service]
Type=oneshot
RemainAfterExit=true
StandardOutput=journal
ExecStart=/home/deck/.mk4_ws/src/steam_deck_bringup/scripts/controller.sh

[Install]
WantedBy=default.target
```

I have also added a line to the sudoer.d to allow it to be run with the sudo password:
`<user> <hostname> =NOPASSWD: /usr/bin/systemctl /home/<user>/sc-controller/run.sh

where i've filled <user> and <hostname> with the details of my steam deck.

Thanks in advance!
Rebecca

**Comment by Ryochan7** [comment]
You would normally want to invoke daemon.sh if you want to run the program with no GUI; you would also have to make sure the GUI does not kill the daemon on exiting. Depending on your desktop environment, you might be able to add an autostart entry to have the DE start run.sh when the environment finishes launching. Editing .xinitrc might be overkill for trying to get SC Controller to start automatically with the X server.
