### ISSUE TITLE
Running daemon instance is too old (version 0.4.7, expected 0.4.8)

### ISSUE THREAD

**Issue by toby63** [Ryochan7/sc-controller#9]
This message is shown in terminal during startup.
 I assume it is only a version naming "issue".

**Comment by Ryochan7** [comment]
Do you have some remnants of a previous SC Controller install on your system? The latest daemon reports version 0.4.8 as expected and the GUI does not complain about a version mismatch.

**Comment by toby63** [comment]
> Do you have some remnants of a previous SC Controller install on your system?

Yes that was the case, sry for the inconvenience.
I deleted the daemon in the user folder and it works as expected.
Still it would be good if a new version would "update" the daemon, but maybe thats a case for upstream.
