### ISSUE TITLE
Steam Deck controls shown for Steam controller

### ISSUE THREAD

**Issue by UltraBlackLinux** [Ryochan7/sc-controller#96]
![image](https://github.com/Ryochan7/sc-controller/assets/62404294/f84addd8-095d-4538-b03d-b40ab71d0921)
All apart from the three dots button are grayed out, and the three dots button cannot be used on the SC.
Why are they shown in the first place?

**Comment by Ryochan7** [comment]
Not sure but it has always been like that. Not sure if there is an easy way to hide elements and keep the layout decent. Not going to worry about it.
