### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by stijnb1234** [Ryochan7/sc-controller#99]
File "/usr/local/lib/python3.10/dist-packages/scc/parser.py", line 256
    		except ValueError, e:
    		       ^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

**Comment by Ryochan7** [comment]
You are using the wrong branch. master points to code from the kozec repo. The python3 branch is the default branch used in this repo and that code has already been refactored in that branch.
